### ISSUE TITLE
file.upload api is deprecated and doesn't work since 2024-05-08 for new apps

### ISSUE THREAD

**Issue by augustr** [dlford/frigate-slack-alerts#10]
Hi and thanks for an awesome app!

When the app tries to upload snapshots it fails with "method_deprecated". After some digging, it seems to be because the slack api files.upload is deprecated and for newly created slack apps it no longer works. The following is to be used instead:
https://api.slack.com/messaging/files#uploading_files

Any plans to fix this?

**Comment by dlford** [comment]
@augustr thanks for bringing this to my attention! I'll get it fixed when I have some free time.

**Comment by augustr** [comment]
I made a pull request for a fix now (although I didn't get the linkage to this issue correctly). Have a look. It works for me, but can be further refined to support teams with lots of channels.
