### ISSUE TITLE
Clip support

### ISSUE THREAD

**Issue by marktheunissen** [dlford/frigate-slack-alerts#18]
Hi there, thanks for this project, wondering what it would take to add clip support? Currently I can see the snapshots coming through on alert but no video clips. 

Here's a Go project that sends Frigate video clips to Telegram: https://github.com/OldTyT/frigate-telegram/blob/main/internal/frigate/frigate.go#L252-L268

Looks like there is a HasClip bool passed on the event and it grabs it from the API.

Just wondering if you've thought about this at all. Thanks

**Comment by dlford** [comment]
That's an interesting idea.

For me, having a quick snapshot to glance at is kind of ideal, knowing I can just jump to the Frigate app if I feel the need to watch the video.

That said, I could see this being an optional preference for other users in the future.

Currently I plan on adding Gotify support and renaming this project to just `frigate-alerts` in the near future, but if there was a good PR for clip support before I get around to it I'd happily merge it in.

**Comment by dlford** [comment]
This issue has been migrated to https://github.com/dlford/frigate-alerts/issues/1
